# Generated by Django 5.0.1 on 2024-01-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_review_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=64)),
                ('abbreviation', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.ManyToManyField(blank=True, null=True, related_name='Currency', to='auctions.currencie'),
        ),
    ]
