# Generated by Django 5.0.1 on 2024-01-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_currencie_listing_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.ManyToManyField(related_name='Currency', to='auctions.currencie'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
