# Generated by Django 5.0.1 on 2024-01-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_currency_alter_listing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='currency',
            new_name='currency_id',
        ),
    ]
