# Generated by Django 5.0.1 on 2024-01-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_currency_listing_currency_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='brand_id',
            field=models.ManyToManyField(related_name='Brand', to='auctions.brand'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category_id',
            field=models.ManyToManyField(related_name='Category', to='auctions.categorie'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
