# Generated by Django 5.0.1 on 2024-01-25 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_brand_id_alter_listing_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='currency_id',
        ),
        migrations.AddField(
            model_name='listing',
            name='brand_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Brand', to='auctions.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='currency_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Currency', to='auctions.currencie'),
            preserve_default=False,
        ),
    ]
