# Generated by Django 5.0.1 on 2024-01-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listing_brand_id_remove_listing_currency_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='currency_id',
        ),
        migrations.DeleteModel(
            name='Currencie',
        ),
    ]
