# Generated by Django 5.0.1 on 2024-01-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listing_currency_id_delete_currencie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='end_time',
        ),
    ]
