# Generated by Django 5.0.1 on 2024-01-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_listing_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='buy_now_price',
        ),
    ]
