# Generated by Django 5.0.1 on 2024-01-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listing_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing_id',
            field=models.ManyToManyField(related_name='watchlist', to='auctions.listing'),
        ),
    ]
