# Generated by Django 5.0.1 on 2024-01-27 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_watchlist_listing_id_watchlist_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='auction_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Listing_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
